name: deploy
on: push
jobs:
  deploy:
    name: build image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lib_franka_tag:
          [
            0.2.0,
            0.3.0,
            0.5.0,
            0.7.0,
            0.7.1,
            0.8.0,
            0.9.0,
            0.9.1,
            0.9.2,
            0.10.0,
          ]
        franka_ros_tag:
          [
            0.1.0,
            0.1.1,
            0.1.2,
            0.10.0,
            0.10.1,
            0.2.0,
            0.2.1,
            0.2.2,
            0.3.0,
            0.4.0,
            0.4.1,
            0.5.0,
            0.6.0,
            0.7.0,
            0.7.1,
            0.8.0,
            0.8.1,
            0.8.2,
            0.9.0,
            0.9.1,
          ]
        ros_distro: [melodic, noetic, foxy, humble]
    steps:
      - name: Create ${{ matrix.lib_franka_tag }}, ${{ matrix.franka_ros_tag }}, ${{ matrix.ros_distro }}
        run: echo "${{ matrix.lib_franka_tag }}, ${{ matrix.franka_ros_tag }}, ${{ matrix.ros_distro }} "
#      - name: checkout code
#        uses: actions/checkout@master
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: build and push to docker
#        uses: docker/build-push-action@v2
#        with:
#          tags: rafa606/franka-control
#          push: true
#		  platforms: linux/amd64,linux/arm64
